### ISSUE TITLE
Mockito verify suspend function called

### ISSUE THREAD

**Issue by GregHib** [hestia-rsps/hestia#52]
`verify(mock).suspend()`

Minimum reproducible example:
```
package worlds.gregs.hestia.core.plugins.dialogue.systems

import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Test
import org.mockito.Mockito
import org.mockito.Mockito.`when`
import org.mockito.Mockito.mock

internal class SuspendTest {

    interface Suspendable {
        suspend fun suspend()
    }

    fun calledElsewhere(mock: Suspendable) = runBlocking {
        mock.suspend()
    }

    @Test
    fun `Suspend test`() = runBlocking {
        //Given
        val mock = mock(Suspendable::class.java)
        `when`(mock.suspend()).thenReturn(Unit)
        //When
        calledElsewhere(mock)
        //Then
        Mockito.verify(mock).suspend()
    }

}
```

```
Argument(s) are different! Wanted:
suspendable.suspend(
    Continuation at worlds.gregs.hestia.core.plugins.dialogue.systems.SuspendTest$Suspend test$1.invokeSuspend(SuspendTest.kt:27)
);
-> at worlds.gregs.hestia.core.plugins.dialogue.systems.SuspendTest$Suspend test$1.invokeSuspend(SuspendTest.kt:27)
Actual invocation has different arguments:
suspendable.suspend(
    Continuation at worlds.gregs.hestia.core.plugins.dialogue.systems.SuspendTest$calledElsewhere$1.invokeSuspend(SuspendTest.kt:16)
);
-> at worlds.gregs.hestia.core.plugins.dialogue.systems.SuspendTest$calledElsewhere$1.invokeSuspend(SuspendTest.kt:16)
```

**Comment by GregHib** [comment]
Used Mockk instead se3906f625d7f05c5bac8f7934fbdf7bbedb18ae5b
Mockito usage deprecated #59
